# Generated by Django 6.1 on 2026-08-28 17:41

import core.crypto
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TotpDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('secret', core.crypto.EncryptedTextField(verbose_name='TOTP 密钥(base32,落库加密)')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='绑定确认时间')),
                ('last_step', models.BigIntegerField(default=0, verbose_name='最后使用的时间步')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='最后验证时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='totp', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '两步验证绑定',
                'verbose_name_plural': '两步验证绑定',
            },
        ),
        migrations.CreateModel(
            name='LoginAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=150, verbose_name='用户名')),
                ('result', models.CharField(choices=[('ok', '登录成功'), ('bad_password', '密码错误'), ('bad_otp', '验证码错误'), ('otp_required', '待输入验证码'), ('inactive', '账号已停用'), ('locked', '已锁定(失败次数过多)'), ('logout', '退出登录')], db_index=True, max_length=20, verbose_name='结果')),
                ('used_2fa', models.BooleanField(default=False, verbose_name='走了两步验证')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='来源 IP')),
                ('user_agent', models.CharField(blank=True, max_length=300, verbose_name='浏览器标识')),
                ('detail', models.CharField(blank=True, max_length=200, verbose_name='补充说明')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='时间')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='login_audits', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '登录审计',
                'verbose_name_plural': '登录审计',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at', 'result'], name='accounts_lo_created_4418c5_idx')],
            },
        ),
        migrations.CreateModel(
            name='RecoveryCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_hash', models.CharField(db_index=True, max_length=64, verbose_name='恢复码哈希')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='生成时间')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='使用时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recovery_codes', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '恢复码',
                'verbose_name_plural': '恢复码',
                'indexes': [models.Index(fields=['user', 'used_at'], name='accounts_re_user_id_51e9a4_idx')],
            },
        ),
    ]
