# Generated by Django 6.1 on 2026-08-28 12:03

import django.db.models.functions.comparison
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netcheck', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='probetarget',
            name='uniq_probe_endpoint',
        ),
        migrations.AddConstraint(
            model_name='probetarget',
            constraint=models.UniqueConstraint(models.F('group'), models.F('host'), models.F('protocol'), django.db.models.functions.comparison.Coalesce('port', models.Value(0)), name='uniq_probe_endpoint_in_group'),
        ),
    ]
