# Generated by Django 6.1 on 2026-08-28 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netcheck', '0002_remove_probetarget_uniq_probe_endpoint_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetentionPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_hours', models.PositiveIntegerField(default=48, help_text='磁盘的主要消费者。一条 1 秒频率的线路一天约 86400 行', verbose_name='原始秒级样本保留(小时)')),
                ('rollup_1m_days', models.PositiveIntegerField(default=7, verbose_name='1 分钟桶保留(天)')),
                ('rollup_5m_days', models.PositiveIntegerField(default=30, verbose_name='5 分钟桶保留(天)')),
                ('rollup_1h_days', models.PositiveIntegerField(default=0, help_text='0 = 永久。一条线路一年才 8760 行,是唯一能回答「去年这条线怎么样」的数据', verbose_name='1 小时桶保留(天)')),
                ('event_days', models.PositiveIntegerField(default=0, help_text='0 = 永久。事件是故障复盘的材料,建议别删', verbose_name='事件保留(天)')),
                ('notify_log_days', models.PositiveIntegerField(default=30, verbose_name='推送记录保留(天)')),
                ('login_audit_days', models.PositiveIntegerField(default=180, verbose_name='登录审计保留(天)')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('updated_by', models.CharField(blank=True, max_length=64, verbose_name='最后修改人')),
            ],
            options={
                'verbose_name': '数据保留策略',
                'verbose_name_plural': '数据保留策略',
            },
        ),
    ]
