# Generated by Django 6.1 on 2026-09-02 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netcheck', '0004_devicebackup_firewallpolicy_server_serverinterface_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='backup_check_unsaved',
            field=models.BooleanField(default=True, help_text='只对 Cisco 有效(比对 running-config 和 startup-config)。**代价是每次备份多取一份配置**,时间大约翻倍。FortiOS 改完即存,没有这个概念', verbose_name='检查配置是否未保存'),
        ),
        migrations.AddField(
            model_name='device',
            name='config_checked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='最后检查时间'),
        ),
        migrations.AddField(
            model_name='device',
            name='config_unsaved',
            field=models.BooleanField(blank=True, null=True, verbose_name='配置未保存'),
        ),
        migrations.AddField(
            model_name='device',
            name='config_unsaved_lines',
            field=models.IntegerField(blank=True, help_text='running 和 startup 之间的差异行数。具体 diff 在 meta.unsaved_diff 里', null=True, verbose_name='未保存的差异行数'),
        ),
        migrations.AlterField(
            model_name='event',
            name='kind',
            field=models.CharField(choices=[('down', '断线'), ('loss', '丢包'), ('latency', '延迟'), ('jitter', '抖动'), ('anomaly', '异常'), ('device_down', '设备失联'), ('cpu_high', 'CPU 过高'), ('mem_high', '内存过高'), ('temp_high', '温度过高'), ('if_down', '接口 Down'), ('if_error', '接口错包'), ('if_saturated', '接口带宽饱和'), ('ha_change', 'HA 状态切换'), ('session_high', '会话数过高'), ('psu_fault', '电源异常'), ('server_down', '服务器失联'), ('disk_high', '磁盘空间不足'), ('load_high', '负载过高'), ('backup_failed', '配置备份失败'), ('config_changed', '配置发生变更'), ('config_unsaved', '配置未保存')], db_index=True, max_length=16, verbose_name='事件类型'),
        ),
    ]
