# Generated by Django 6.1 on 2026-09-02 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netcheck', '0005_device_backup_check_unsaved_device_config_checked_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='collect_neighbors',
            field=models.BooleanField(default=True, help_text='「这个口对面接的是谁」。多走两张表(LLDP + CDP),邻居关系变化很慢所以代价不大 —— 但它是排障时第一个要看的东西', verbose_name='采集邻居(LLDP/CDP)'),
        ),
        migrations.AlterField(
            model_name='event',
            name='kind',
            field=models.CharField(choices=[('down', '断线'), ('loss', '丢包'), ('latency', '延迟'), ('jitter', '抖动'), ('anomaly', '异常'), ('device_down', '设备失联'), ('cpu_high', 'CPU 过高'), ('mem_high', '内存过高'), ('temp_high', '温度过高'), ('if_down', '接口 Down'), ('if_error', '接口错包'), ('if_saturated', '接口带宽饱和'), ('ha_change', 'HA 状态切换'), ('session_high', '会话数过高'), ('psu_fault', '电源异常'), ('server_down', '服务器失联'), ('disk_high', '磁盘空间不足'), ('load_high', '负载过高'), ('backup_failed', '配置备份失败'), ('config_changed', '配置发生变更'), ('config_unsaved', '配置未保存'), ('neighbor_change', '邻居变化')], db_index=True, max_length=16, verbose_name='事件类型'),
        ),
        migrations.CreateModel(
            name='DeviceNeighbor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('meta', models.JSONField(blank=True, default=dict, verbose_name='META 扩展')),
                ('protocol', models.CharField(db_index=True, help_text='lldp / cdp', max_length=8, verbose_name='发现协议')),
                ('local_if_index', models.IntegerField(blank=True, null=True, verbose_name='本地 ifIndex')),
                ('local_if_name', models.CharField(max_length=128, verbose_name='本地接口')),
                ('remote_device', models.CharField(blank=True, max_length=255, verbose_name='对端设备名')),
                ('remote_port', models.CharField(blank=True, max_length=255, verbose_name='对端接口')),
                ('remote_platform', models.CharField(blank=True, help_text='CDP 的 cdpCachePlatform 或 LLDP 的 sysDesc 头部', max_length=255, verbose_name='对端型号/平台')),
                ('remote_mgmt_ip', models.CharField(blank=True, max_length=64, verbose_name='对端管理地址')),
                ('remote_chassis_id', models.CharField(blank=True, help_text='LLDP 的机箱标识,通常是对端的一个 MAC。**换设备时它会变**,是判断「对面是不是同一台机器」最可靠的字段', max_length=128, verbose_name='对端 chassis id')),
                ('first_seen', models.DateTimeField(verbose_name='首次发现')),
                ('last_seen', models.DateTimeField(db_index=True, verbose_name='最后确认')),
                ('changed_at', models.DateTimeField(blank=True, help_text='对端设备名/接口/chassis id 变过的时间 —— 通常意味着有人动了线', null=True, verbose_name='最后变化时间')),
                ('raw', models.JSONField(blank=True, default=dict, verbose_name='原始记录')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='neighbors', to='netcheck.device', verbose_name='设备')),
                ('matched_device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='neighbor_of', to='netcheck.device', verbose_name='对端(已纳管)')),
            ],
            options={
                'verbose_name': '设备邻居',
                'verbose_name_plural': '设备邻居',
                'ordering': ['device_id', 'local_if_index', 'protocol'],
                'indexes': [models.Index(fields=['device', 'local_if_index'], name='idx_neighbor_local'), models.Index(fields=['remote_device'], name='idx_neighbor_remote')],
                'constraints': [models.UniqueConstraint(fields=('device', 'protocol', 'local_if_name', 'remote_device', 'remote_port'), name='uniq_neighbor_per_port', nulls_distinct=False)],
            },
        ),
    ]
