# Generated by Django 6.1 on 2026-09-03 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netcheck', '0006_device_collect_neighbors_alter_event_kind_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='os_type',
            field=models.CharField(choices=[('linux', 'Linux / 类 Unix'), ('esxi', 'VMware ESXi')], db_index=True, default='linux', help_text='决定走哪一套采集命令。选错了指标会**全是空的而且不报错** —— ESXi 上没有 /proc/stat 也没有 /proc/meminfo,但 shell 跑得通', max_length=12, verbose_name='系统类型'),
        ),
        migrations.AlterField(
            model_name='server',
            name='collect_processes',
            field=models.BooleanField(default=True, help_text='Linux:多一条 ps,换来「是谁在吃 CPU」。ESXi:多一条 `esxcli vm process list`,换来「这台宿主上正在跑哪些虚拟机」', verbose_name='采集进程 / 虚拟机清单'),
        ),
        migrations.AlterField(
            model_name='server',
            name='load_warn',
            field=models.FloatField(default=1.5, help_text='判的是 load1 ÷ 核数。1.0 = 刚好跑满。**ESXi 没有 loadavg,这两项不生效**', verbose_name='负载警告线(每核)'),
        ),
        migrations.AlterField(
            model_name='server',
            name='net_interface',
            field=models.CharField(blank=True, help_text='留空 = 自动选。**不要把所有网卡加起来** —— docker0 / veth / br- 这些虚拟口会把同一份流量数两三遍。Linux 上自动 = 默认路由那块;ESXi 上填 vmnicN,自动 = 累计收字节最多的那块 Up 上行口', max_length=32, verbose_name='流量统计网卡'),
        ),
    ]
