# Generated by Django 6.1 on 2026-09-03 05:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netcheck', '0007_server_os_type_alter_server_collect_processes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirewallVip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vdom', models.CharField(blank=True, default='root', max_length=64, verbose_name='VDOM')),
                ('name', models.CharField(help_text='策略的目的地址里引用的就是这个名字', max_length=128, verbose_name='名称')),
                ('seq', models.IntegerField(default=0, verbose_name='顺序')),
                ('vip_type', models.CharField(choices=[('static-nat', '静态 NAT'), ('server-load-balance', '负载均衡'), ('dns-translation', 'DNS 转换'), ('fqdn', 'FQDN'), ('other', '其它')], default='static-nat', max_length=24, verbose_name='类型')),
                ('ext_intf', models.JSONField(blank=True, default=list, verbose_name='外部接口')),
                ('ext_ip', models.CharField(blank=True, help_text='可能是一段范围', max_length=128, verbose_name='外部地址')),
                ('ext_port', models.CharField(blank=True, help_text='**空 = 所有端口**(整机映射),不是「没配」。也可能是 8080-8090 这样的范围', max_length=64, verbose_name='外部端口')),
                ('mapped_ip', models.CharField(blank=True, max_length=256, verbose_name='内部地址')),
                ('mapped_port', models.CharField(blank=True, max_length=64, verbose_name='内部端口')),
                ('protocol', models.CharField(blank=True, help_text='tcp / udp / sctp / icmp。空表示所有协议', max_length=12, verbose_name='协议')),
                ('port_forward', models.BooleanField(default=False, help_text='关 = 整机 1:1 映射(所有端口都进去),开 = 只映射指定端口', verbose_name='端口映射')),
                ('comment', models.CharField(blank=True, max_length=255, verbose_name='备注')),
                ('uuid', models.CharField(blank=True, max_length=64, verbose_name='UUID')),
                ('raw', models.JSONField(blank=True, default=dict, verbose_name='原始记录')),
                ('synced_at', models.DateTimeField(db_index=True, verbose_name='同步时间')),
                ('method', models.CharField(blank=True, help_text='api / ssh', max_length=8, verbose_name='同步通道')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vips', to='netcheck.device', verbose_name='设备')),
            ],
            options={
                'verbose_name': '防火墙映射',
                'verbose_name_plural': '防火墙映射',
                'ordering': ['device_id', 'vdom', 'seq', 'name'],
                'indexes': [models.Index(fields=['device', 'seq'], name='idx_vip_device_seq')],
                'constraints': [models.UniqueConstraint(fields=('device', 'vdom', 'name'), name='uniq_vip_per_device_vdom')],
            },
        ),
    ]
