# Generated by Django 6.1 on 2026-09-03 05:40

import core.crypto
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netcheck', '0008_firewallvip'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdracHost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('meta', models.JSONField(blank=True, default=dict, verbose_name='META 扩展')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='名称')),
                ('host', models.GenericIPAddressField(db_index=True, help_text='**带外管理口的地址,不是服务器自己的 IP** —— 两者是两个不同的地址', verbose_name='iDRAC 地址')),
                ('port', models.IntegerField(default=443, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(65535)], verbose_name='端口')),
                ('username', models.CharField(default='root', max_length=64, verbose_name='用户名')),
                ('password', core.crypto.EncryptedTextField(blank=True, default='', verbose_name='密码')),
                ('verify_tls', models.BooleanField(default=False, help_text='iDRAC 出厂是自签证书,默认关。换过正式证书再打开', verbose_name='校验 TLS 证书')),
                ('site', models.CharField(blank=True, max_length=64, verbose_name='机房/位置')),
                ('role', models.CharField(blank=True, help_text='只用于展示分组', max_length=64, verbose_name='用途')),
                ('interval_seconds', models.IntegerField(default=300, help_text='带外的东西变化很慢(温度除外),**最小 60 秒**。iDRAC 的 BMC 是一颗很弱的处理器,打太勤会把它自己拖慢,严重时管理界面登不进去 —— 而那正是出事时要用的东西', validators=[django.core.validators.MinValueValidator(60), django.core.validators.MaxValueValidator(86400)], verbose_name='采集频率(秒)')),
                ('timeout_ms', models.IntegerField(default=15000, help_text='BMC 响应慢是常态,别设太短', validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(120000)], verbose_name='超时(毫秒)')),
                ('temp_warn_c', models.IntegerField(default=70, verbose_name='温度警告线(℃)')),
                ('temp_crit_c', models.IntegerField(default=85, verbose_name='温度严重线(℃)')),
                ('temp_delta_warn_c', models.IntegerField(default=15, help_text='同一台机器上两个 CPU 温度差这么多 = 那一颗的散热有问题,不是机房热。0 = 不判', verbose_name='同机温差警告(℃)')),
                ('ssd_life_warn_pct', models.IntegerField(default=10, help_text='剩余写入寿命低于这个数就告警。**机械盘没有这个概念,不参与判定**', verbose_name='SSD 剩余寿命警告(%)')),
                ('event_window_days', models.IntegerField(default=7, help_text='SEL(硬件事件日志)**不会自动清**,一台机器上留着几年前的记录很正常。只看这个窗口内的 —— 一条永远都在的红等于没有红', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(365)], verbose_name='硬件日志回看天数')),
                ('fail_threshold', models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(1)], verbose_name='连续失败次数开事件')),
                ('recover_threshold', models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(1)], verbose_name='连续正常次数关事件')),
                ('collect_events', models.BooleanField(default=True, help_text='多一次请求。SEL 是「这台机器过去发生过什么」的唯一来源', verbose_name='采集硬件日志(SEL)')),
                ('enabled', models.BooleanField(db_index=True, default=True, verbose_name='启用')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('state', models.CharField(choices=[('unknown', '未知'), ('up', '正常'), ('degraded', '劣化'), ('down', '中断')], db_index=True, default='unknown', max_length=12, verbose_name='当前状态')),
                ('last_collected_at', models.DateTimeField(blank=True, null=True, verbose_name='最后采集时间')),
                ('last_error', models.CharField(blank=True, max_length=255, verbose_name='最后错误')),
                ('consecutive_fail', models.IntegerField(default=0, verbose_name='连续失败次数')),
                ('consecutive_ok', models.IntegerField(default=0, verbose_name='连续正常次数')),
                ('model_name', models.CharField(blank=True, max_length=128, verbose_name='型号')),
                ('manufacturer', models.CharField(blank=True, max_length=64, verbose_name='厂商')),
                ('service_tag', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='服务编号')),
                ('bios_version', models.CharField(blank=True, max_length=64, verbose_name='BIOS 版本')),
                ('idrac_firmware', models.CharField(blank=True, max_length=64, verbose_name='iDRAC 固件')),
                ('system_hostname', models.CharField(blank=True, max_length=128, verbose_name='系统主机名')),
                ('power_state', models.CharField(blank=True, max_length=16, verbose_name='电源状态')),
            ],
            options={
                'verbose_name': '带外主机(iDRAC)',
                'verbose_name_plural': '带外主机(iDRAC)',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='IdracSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.DateTimeField(db_index=True, verbose_name='时间')),
                ('reachable', models.BooleanField(default=True, verbose_name='可达')),
                ('latency_ms', models.FloatField(blank=True, null=True, verbose_name='响应耗时(ms)')),
                ('power_watts', models.FloatField(blank=True, null=True, verbose_name='整机功耗(W)')),
                ('inlet_temp_c', models.FloatField(blank=True, help_text='机房环境温度的最好代理 —— 它高说明是机房热,不是这台机器的问题', null=True, verbose_name='进风温度(℃)')),
                ('max_temp_c', models.FloatField(blank=True, null=True, verbose_name='最高温度(℃)')),
                ('temp_delta_c', models.FloatField(blank=True, null=True, verbose_name='同机最大温差(℃)')),
                ('fan_max_rpm', models.IntegerField(blank=True, null=True, verbose_name='最高风扇转速')),
                ('disk_total', models.IntegerField(blank=True, null=True, verbose_name='物理盘数')),
                ('disk_bad', models.IntegerField(blank=True, null=True, verbose_name='异常物理盘')),
                ('disk_unknown', models.IntegerField(blank=True, null=True, verbose_name='状态未知物理盘')),
                ('psu_total', models.IntegerField(blank=True, null=True, verbose_name='电源数')),
                ('psu_bad', models.IntegerField(blank=True, null=True, verbose_name='异常电源')),
                ('memory_total', models.IntegerField(blank=True, null=True, verbose_name='内存条数')),
                ('memory_bad', models.IntegerField(blank=True, null=True, verbose_name='异常内存条')),
                ('fan_total', models.IntegerField(blank=True, null=True, verbose_name='风扇数')),
                ('fan_bad', models.IntegerField(blank=True, null=True, verbose_name='异常风扇')),
                ('vdisk_total', models.IntegerField(blank=True, null=True, verbose_name='RAID 卷数')),
                ('vdisk_bad', models.IntegerField(blank=True, null=True, verbose_name='降级 RAID 卷')),
                ('health', models.CharField(choices=[('ok', '正常'), ('warning', '警告'), ('critical', '严重'), ('unknown', '未知')], default='unknown', max_length=12, verbose_name='整机健康')),
                ('extra', models.JSONField(blank=True, default=dict, verbose_name='明细')),
                ('error', models.CharField(blank=True, max_length=255, verbose_name='错误')),
            ],
            options={
                'verbose_name': '带外样本',
                'verbose_name_plural': '带外样本',
                'ordering': ['-ts'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='event',
            name='uniq_open_event_per_source_kind',
        ),
        migrations.AlterField(
            model_name='event',
            name='kind',
            field=models.CharField(choices=[('down', '断线'), ('loss', '丢包'), ('latency', '延迟'), ('jitter', '抖动'), ('anomaly', '异常'), ('device_down', '设备失联'), ('cpu_high', 'CPU 过高'), ('mem_high', '内存过高'), ('temp_high', '温度过高'), ('if_down', '接口 Down'), ('if_error', '接口错包'), ('if_saturated', '接口带宽饱和'), ('ha_change', 'HA 状态切换'), ('session_high', '会话数过高'), ('psu_fault', '电源异常'), ('server_down', '服务器失联'), ('disk_high', '磁盘空间不足'), ('load_high', '负载过高'), ('backup_failed', '配置备份失败'), ('config_changed', '配置发生变更'), ('config_unsaved', '配置未保存'), ('neighbor_change', '邻居变化'), ('idrac_down', '带外失联'), ('hw_health', '整机健康告警'), ('hw_disk', '物理盘异常'), ('hw_raid', 'RAID 卷降级'), ('hw_memory', '内存条异常'), ('hw_fan', '风扇异常'), ('hw_voltage', '电压异常'), ('ssd_worn', 'SSD 寿命将尽')], db_index=True, max_length=16, verbose_name='事件类型'),
        ),
        migrations.AlterField(
            model_name='event',
            name='source_type',
            field=models.CharField(choices=[('probe', '线路拨测'), ('device', '设备'), ('interface', '设备接口'), ('server', '服务器'), ('idrac', '带外(iDRAC)')], db_index=True, max_length=12, verbose_name='来源类型'),
        ),
        migrations.AddField(
            model_name='idrachost',
            name='server',
            field=models.ForeignKey(blank=True, help_text='填了的话页面上两张卡片会连起来。不填不影响采集', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='idrac_hosts', to='netcheck.server', verbose_name='对应的服务器'),
        ),
        migrations.AddField(
            model_name='event',
            name='idrac',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='netcheck.idrachost', verbose_name='带外主机'),
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.UniqueConstraint(condition=models.Q(('resolved_at__isnull', True)), fields=('source_type', 'target', 'device', 'interface', 'server', 'idrac', 'kind'), name='uniq_open_event_per_source_kind', nulls_distinct=False),
        ),
        migrations.AddField(
            model_name='idracsample',
            name='idrac',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='netcheck.idrachost', verbose_name='带外主机'),
        ),
        migrations.AddIndex(
            model_name='idrachost',
            index=models.Index(fields=['enabled', 'state'], name='netcheck_id_enabled_92e5e2_idx'),
        ),
        migrations.AddConstraint(
            model_name='idrachost',
            constraint=models.UniqueConstraint(fields=('host', 'port'), name='uniq_idrac_endpoint'),
        ),
        migrations.AddIndex(
            model_name='idracsample',
            index=models.Index(fields=['idrac', '-ts'], name='idx_idrac_sample'),
        ),
    ]
