# Generated by Django 6.1 on 2026-09-03 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netcheck', '0009_idrachost_idracsample_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirewallAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vdom', models.CharField(blank=True, default='root', max_length=64, verbose_name='VDOM')),
                ('name', models.CharField(help_text='策略的源/目的地址里引用的就是这个名字', max_length=128, verbose_name='名称')),
                ('seq', models.IntegerField(default=0, verbose_name='顺序')),
                ('addr_type', models.CharField(choices=[('ipmask', '子网'), ('iprange', '地址段'), ('fqdn', '域名'), ('geography', '国家/地区'), ('wildcard', '通配掩码'), ('dynamic', '动态(SDN/标签)'), ('group', '地址组'), ('other', '其它')], default='ipmask', max_length=16, verbose_name='类型')),
                ('is_group', models.BooleanField(db_index=True, default=False, verbose_name='是地址组')),
                ('value', models.CharField(blank=True, max_length=255, verbose_name='地址值')),
                ('members', models.JSONField(blank=True, default=list, verbose_name='成员')),
                ('comment', models.CharField(blank=True, max_length=255, verbose_name='备注')),
                ('interface', models.CharField(blank=True, max_length=64, verbose_name='绑定接口')),
                ('uuid', models.CharField(blank=True, max_length=64, verbose_name='UUID')),
                ('raw', models.JSONField(blank=True, default=dict, verbose_name='原始记录')),
                ('synced_at', models.DateTimeField(db_index=True, verbose_name='同步时间')),
                ('method', models.CharField(blank=True, help_text='api / ssh', max_length=8, verbose_name='同步通道')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='netcheck.device', verbose_name='设备')),
            ],
            options={
                'verbose_name': '防火墙地址对象',
                'verbose_name_plural': '防火墙地址对象',
                'ordering': ['device_id', 'vdom', 'name'],
                'indexes': [models.Index(fields=['device', 'is_group'], name='idx_addr_device_group'), models.Index(fields=['device', 'name'], name='idx_addr_device_name')],
                'constraints': [models.UniqueConstraint(fields=('device', 'vdom', 'name'), name='uniq_address_per_device_vdom')],
            },
        ),
    ]
