# Generated by Django 6.1 on 2026-09-03 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netcheck', '0010_firewalladdress'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirewallService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vdom', models.CharField(blank=True, default='root', max_length=64, verbose_name='VDOM')),
                ('name', models.CharField(help_text='策略的服务里引用的就是这个名字', max_length=128, verbose_name='名称')),
                ('seq', models.IntegerField(default=0, verbose_name='顺序')),
                ('is_group', models.BooleanField(db_index=True, default=False, verbose_name='是服务组')),
                ('value', models.CharField(blank=True, max_length=255, verbose_name='端口 / 协议')),
                ('protocol', models.CharField(blank=True, help_text='TCP/UDP/SCTP / ICMP / IP', max_length=32, verbose_name='协议')),
                ('members', models.JSONField(blank=True, default=list, verbose_name='成员')),
                ('category', models.CharField(blank=True, max_length=64, verbose_name='分类')),
                ('comment', models.CharField(blank=True, max_length=255, verbose_name='备注')),
                ('predefined', models.BooleanField(default=False, verbose_name='预定义服务')),
                ('raw', models.JSONField(blank=True, default=dict, verbose_name='原始记录')),
                ('synced_at', models.DateTimeField(db_index=True, verbose_name='同步时间')),
                ('method', models.CharField(blank=True, help_text='api / ssh', max_length=8, verbose_name='同步通道')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='netcheck.device', verbose_name='设备')),
            ],
            options={
                'verbose_name': '防火墙服务对象',
                'verbose_name_plural': '防火墙服务对象',
                'ordering': ['device_id', 'vdom', 'name'],
                'indexes': [models.Index(fields=['device', 'is_group'], name='idx_svc_device_group'), models.Index(fields=['device', 'name'], name='idx_svc_device_name')],
                'constraints': [models.UniqueConstraint(fields=('device', 'vdom', 'name'), name='uniq_service_per_device_vdom')],
            },
        ),
    ]
