# Generated by Django 6.1 on 2026-09-03 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netcheck', '0011_firewallservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='collect_sdwan',
            field=models.BooleanField(default=False, help_text='仅 FortiGate。**强烈建议配 API Token** —— monitor/virtual-wan/health-check 一次给全部成员的延迟/抖动/丢包/达标情况;SSH 的 `diagnose sys sdwan health-check` 格式在版本间有出入', verbose_name='采集 SD-WAN SLA'),
        ),
        migrations.AddField(
            model_name='device',
            name='last_sdwan_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='最后 SD-WAN 采集时间'),
        ),
        migrations.AddField(
            model_name='device',
            name='last_sdwan_error',
            field=models.CharField(blank=True, max_length=255, verbose_name='最后 SD-WAN 采集错误'),
        ),
        migrations.AddField(
            model_name='device',
            name='sla_latency_warn_ms',
            field=models.FloatField(blank=True, help_text='留空 = 只按设备自己的 SLA 判定。填了则延迟超过它也告警(级别 warning)', null=True, verbose_name='SLA 延迟警告线(ms)'),
        ),
        migrations.AddField(
            model_name='device',
            name='sla_loss_warn_pct',
            field=models.FloatField(blank=True, help_text='留空 = 不判', null=True, verbose_name='SLA 丢包警告线(%)'),
        ),
        migrations.AlterField(
            model_name='event',
            name='kind',
            field=models.CharField(choices=[('down', '断线'), ('loss', '丢包'), ('latency', '延迟'), ('jitter', '抖动'), ('anomaly', '异常'), ('device_down', '设备失联'), ('cpu_high', 'CPU 过高'), ('mem_high', '内存过高'), ('temp_high', '温度过高'), ('if_down', '接口 Down'), ('if_error', '接口错包'), ('if_saturated', '接口带宽饱和'), ('ha_change', 'HA 状态切换'), ('session_high', '会话数过高'), ('psu_fault', '电源异常'), ('server_down', '服务器失联'), ('disk_high', '磁盘空间不足'), ('load_high', '负载过高'), ('backup_failed', '配置备份失败'), ('config_changed', '配置发生变更'), ('config_unsaved', '配置未保存'), ('neighbor_change', '邻居变化'), ('idrac_down', '带外失联'), ('hw_health', '整机健康告警'), ('hw_disk', '物理盘异常'), ('hw_raid', 'RAID 卷降级'), ('hw_memory', '内存条异常'), ('hw_fan', '风扇异常'), ('hw_voltage', '电压异常'), ('ssd_worn', 'SSD 寿命将尽'), ('sla_violated', 'SD-WAN SLA 未达标'), ('sdwan_dead', 'SD-WAN 成员失联')], db_index=True, max_length=16, verbose_name='事件类型'),
        ),
        migrations.CreateModel(
            name='SdwanLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vdom', models.CharField(blank=True, default='root', max_length=64, verbose_name='VDOM')),
                ('health_check', models.CharField(help_text='FortiOS 里那个 health-check 的名字', max_length=64, verbose_name='健康检查')),
                ('member', models.CharField(help_text='wan1 / wan2 / ipsec-tunnel…', max_length=64, verbose_name='成员接口')),
                ('server', models.CharField(blank=True, max_length=255, verbose_name='探测目标')),
                ('protocol', models.CharField(blank=True, help_text='ping / http / tcp-echo…', max_length=16, verbose_name='探测协议')),
                ('state', models.CharField(choices=[('alive', '通'), ('dead', '不通'), ('unknown', '未知')], db_index=True, default='unknown', max_length=12, verbose_name='状态')),
                ('latency_ms', models.FloatField(blank=True, null=True, verbose_name='延迟(ms)')),
                ('jitter_ms', models.FloatField(blank=True, null=True, verbose_name='抖动(ms)')),
                ('loss_pct', models.FloatField(blank=True, null=True, verbose_name='丢包率(%)')),
                ('sla_met', models.BooleanField(blank=True, null=True, verbose_name='SLA 达标')),
                ('sla_targets_met', models.IntegerField(blank=True, null=True, verbose_name='达标档数')),
                ('sla_targets_total', models.IntegerField(blank=True, null=True, verbose_name='SLA 档数')),
                ('tx_bps', models.FloatField(blank=True, null=True, verbose_name='出向带宽(bps)')),
                ('rx_bps', models.FloatField(blank=True, null=True, verbose_name='入向带宽(bps)')),
                ('session_count', models.IntegerField(blank=True, null=True, verbose_name='会话数')),
                ('sla_latency_threshold', models.FloatField(blank=True, null=True, verbose_name='门限:延迟(ms)')),
                ('sla_jitter_threshold', models.FloatField(blank=True, null=True, verbose_name='门限:抖动(ms)')),
                ('sla_loss_threshold', models.FloatField(blank=True, null=True, verbose_name='门限:丢包(%)')),
                ('last_change', models.DateTimeField(blank=True, null=True, verbose_name='最后状态变化')),
                ('synced_at', models.DateTimeField(db_index=True, verbose_name='同步时间')),
                ('method', models.CharField(blank=True, help_text='api / ssh', max_length=8, verbose_name='同步通道')),
                ('extra', models.JSONField(blank=True, default=dict, verbose_name='明细')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sdwan_links', to='netcheck.device', verbose_name='设备')),
            ],
            options={
                'verbose_name': 'SD-WAN SLA 链路',
                'verbose_name_plural': 'SD-WAN SLA 链路',
                'ordering': ['device_id', 'vdom', 'health_check', 'member'],
            },
        ),
        migrations.CreateModel(
            name='SdwanSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.DateTimeField(db_index=True, verbose_name='时间')),
                ('state', models.CharField(choices=[('alive', '通'), ('dead', '不通'), ('unknown', '未知')], max_length=12, verbose_name='状态')),
                ('latency_ms', models.FloatField(blank=True, null=True, verbose_name='延迟(ms)')),
                ('jitter_ms', models.FloatField(blank=True, null=True, verbose_name='抖动(ms)')),
                ('loss_pct', models.FloatField(blank=True, null=True, verbose_name='丢包率(%)')),
                ('sla_met', models.BooleanField(blank=True, null=True, verbose_name='SLA 达标')),
                ('tx_bps', models.FloatField(blank=True, null=True, verbose_name='出向带宽(bps)')),
                ('rx_bps', models.FloatField(blank=True, null=True, verbose_name='入向带宽(bps)')),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='netcheck.sdwanlink', verbose_name='链路')),
            ],
            options={
                'verbose_name': 'SD-WAN 采样',
                'verbose_name_plural': 'SD-WAN 采样',
                'ordering': ['-ts'],
            },
        ),
        migrations.AddIndex(
            model_name='sdwanlink',
            index=models.Index(fields=['device', 'state'], name='idx_sdwan_device_state'),
        ),
        migrations.AddConstraint(
            model_name='sdwanlink',
            constraint=models.UniqueConstraint(fields=('device', 'vdom', 'health_check', 'member'), name='uniq_sdwan_link'),
        ),
        migrations.AddIndex(
            model_name='sdwansample',
            index=models.Index(fields=['link', '-ts'], name='idx_sdwan_sample'),
        ),
    ]
