# Generated by Django 6.1 on 2026-09-03 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netcheck', '0012_device_collect_sdwan_device_last_sdwan_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='kind',
            field=models.CharField(choices=[('down', '断线'), ('loss', '丢包'), ('latency', '延迟'), ('jitter', '抖动'), ('anomaly', '异常'), ('device_down', '设备失联'), ('cpu_high', 'CPU 过高'), ('mem_high', '内存过高'), ('temp_high', '温度过高'), ('if_down', '接口 Down'), ('if_error', '接口错包'), ('if_saturated', '接口带宽饱和'), ('ha_change', 'HA 状态切换'), ('session_high', '会话数过高'), ('psu_fault', '电源异常'), ('server_down', '服务器失联'), ('disk_high', '磁盘空间不足'), ('load_high', '负载过高'), ('backup_failed', '配置备份失败'), ('config_changed', '配置发生变更'), ('config_unsaved', '配置未保存'), ('neighbor_change', '邻居变化'), ('idrac_down', '带外失联'), ('hw_health', '整机健康告警'), ('hw_disk', '物理盘异常'), ('hw_raid', 'RAID 卷降级'), ('hw_memory', '内存条异常'), ('hw_fan', '风扇异常'), ('hw_voltage', '电压异常'), ('ssd_worn', 'SSD 寿命将尽'), ('compliance_fail', '配置不合规'), ('policy_risk', '防火墙规则风险'), ('sla_violated', 'SD-WAN SLA 未达标'), ('sdwan_dead', 'SD-WAN 成员失联')], db_index=True, max_length=16, verbose_name='事件类型'),
        ),
    ]
