# Generated by Django 6.1 on 2026-09-03 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netcheck', '0013_alter_event_kind'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='firewallpolicy',
            name='uniq_policy_per_device_vdom',
        ),
        migrations.AddField(
            model_name='firewallpolicy',
            name='acl_name',
            field=models.CharField(blank=True, help_text='Cisco 才有。FortiGate 的策略不属于任何 ACL,这里是空的', max_length=128, verbose_name='ACL 名称'),
        ),
        migrations.AddField(
            model_name='firewallpolicy',
            name='bindings',
            field=models.JSONField(blank=True, default=list, verbose_name='接口绑定'),
        ),
        migrations.AddField(
            model_name='firewallpolicy',
            name='implicit',
            field=models.BooleanField(default=False, verbose_name='隐含规则'),
        ),
        migrations.AddConstraint(
            model_name='firewallpolicy',
            constraint=models.UniqueConstraint(fields=('device', 'vdom', 'acl_name', 'policy_id'), name='uniq_policy_per_device_vdom'),
        ),
    ]
